volumes:
    torcher:
    caddy:

services:
    torcher:
        restart: always
        build:
            context: ./
            dockerfile: torcher.dockerfile
        env_file: ./.env
        volumes:
            - torcher:/var/lib/torcher
        ports:
            - 3030:3030
    caddy:
        env_file: ./.env
        restart: always
        build:
            context: ./
            dockerfile: caddy.dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - caddy:/data
