volumes:
    torcher:

services:
    torcher:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: ./.env
        volumes:
            - torcher:/var/lib/torcher
        ports:
            - 3030:3030
